/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plans/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlan"];
        put: operations["savePlan"];
        post?: never;
        delete: operations["deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-bundles/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-bundles/orders/{orderId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-bundles/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{code}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/recharge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/recharge-orders/{orderId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshWalletRechargeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/recharge-orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWalletRechargeOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/recharge-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWalletRechargeOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post: operations["initiate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders/callbacks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pricing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-bundles/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-bundles/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commercial-plans/{planCode}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteCommercialPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commercial-plans/{planCode}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkoutCommercialPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commercial-plans/orders/{orderId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshCommercialPlanOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commercial-plans/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCommercialPlanOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commercial-plans/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCommercialPlanOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mySubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/can-operate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["canOperate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/owner/{ownerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWalletByOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SavePlanRequest: {
            code?: string;
            name?: string;
            description?: string;
            price?: number;
            currency?: string;
            /** Format: int32 */
            periodDays?: number;
            serviceCodes?: string[];
            active?: boolean;
        };
        ApiResponsePlanResponse: {
            success?: boolean;
            data?: components["schemas"]["PlanResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PlanResponse: {
            code?: string;
            name?: string;
            description?: string;
            price?: number;
            currency?: string;
            /** Format: int32 */
            periodDays?: number;
            serviceCodes?: string[];
            active?: boolean;
        };
        ServiceBundleQuoteRequest: {
            services?: string[];
            /** @enum {string} */
            billingPeriod?: "MONTHLY" | "YEARLY";
        };
        ApiResponseServiceBundleQuoteResponse: {
            success?: boolean;
            data?: components["schemas"]["ServiceBundleQuoteResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ServiceBundleQuoteResponse: {
            billingPeriod?: string;
            lines?: components["schemas"]["ServicePriceResponse"][];
            total?: number;
            currency?: string;
        };
        ServicePriceResponse: {
            serviceCode?: string;
            billingPeriod?: string;
            amount?: number;
            currency?: string;
        };
        ApiResponseServiceBundleOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["ServiceBundleOrderResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ServiceBundleOrderResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            organizationId?: string;
            services?: string[];
            billingPeriod?: string;
            amount?: number;
            currency?: string;
            /** Format: uuid */
            paymentOrderId?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "ACTIVE" | "FAILED" | "CANCELLED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ServiceBundleCheckoutRequest: {
            /** Format: uuid */
            organizationId?: string;
            services?: string[];
            /** @enum {string} */
            billingPeriod?: "MONTHLY" | "YEARLY";
            clientId?: string;
            /** @enum {string} */
            provider?: "MYCOOLPAY" | "STRIPE";
            /** @enum {string} */
            method?: "MOBILE_MONEY" | "CARD";
            payerReference?: string;
            idempotencyKey?: string;
        };
        ApiResponseServiceBundleCheckoutResponse: {
            success?: boolean;
            data?: components["schemas"]["ServiceBundleCheckoutResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ServiceBundleCheckoutResponse: {
            /** Format: uuid */
            orderId?: string;
            /** Format: uuid */
            paymentOrderId?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "ACTIVE" | "FAILED" | "CANCELLED";
            amount?: number;
            currency?: string;
            redirectUrl?: string;
            providerReference?: string;
        };
        PurchaseRequest: {
            /** Format: uuid */
            organizationId?: string;
        };
        ApiResponseSubscriptionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        SubscriptionResponse: {
            /** Format: uuid */
            organizationId?: string;
            planCode?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            paidUntil?: string;
            active?: boolean;
        };
        CreateWalletRequest: {
            /** Format: uuid */
            ownerId?: string;
            ownerName?: string;
        };
        ApiResponseWalletResponse: {
            success?: boolean;
            data?: components["schemas"]["WalletResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        WalletResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ownerId?: string;
            ownerName?: string;
            balance?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TransactionRequest: {
            amount?: number;
            reference?: string;
        };
        ApiResponseTransactionResponse: {
            success?: boolean;
            data?: components["schemas"]["TransactionResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        TransactionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            walletId?: string;
            amount?: number;
            type?: string;
            status?: string;
            reference?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        InitiatePaymentRequest: {
            clientId?: string;
            serviceCode?: string;
            idempotencyKey?: string;
            amount?: number;
            currency?: string;
            /** @enum {string} */
            provider?: "MYCOOLPAY" | "STRIPE";
            /** @enum {string} */
            method?: "MOBILE_MONEY" | "CARD";
            payerReference?: string;
            description?: string;
            callbackUrl?: string;
        };
        ApiResponsePaymentOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["PaymentOrderResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PaymentOrderResponse: {
            id?: string;
            tenantId?: string;
            clientId?: string;
            serviceCode?: string;
            amount?: number;
            currency?: string;
            provider?: string;
            method?: string;
            payerReference?: string;
            status?: string;
            providerReference?: string;
            redirectUrl?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseString: {
            success?: boolean;
            data?: string;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListServicePriceResponse: {
            success?: boolean;
            data?: components["schemas"]["ServicePriceResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListServiceBundleOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["ServiceBundleOrderResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPlanResponse: {
            success?: boolean;
            data?: components["schemas"]["PlanResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListSubscriptionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListTransactionResponse: {
            success?: boolean;
            data?: components["schemas"]["TransactionResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseBoolean: {
            success?: boolean;
            data?: boolean;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPaymentOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["PaymentOrderResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: unknown;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        WalletRechargeRequest: {
            amount?: number;
            currency?: string;
            clientId?: string;
            /** @enum {string} */
            provider?: "MYCOOLPAY" | "STRIPE";
            /** @enum {string} */
            method?: "MOBILE_MONEY" | "CARD";
            payerReference?: string;
            idempotencyKey?: string;
        };
        WalletRechargeOrderResponse: {
            /** Format: uuid */
            orderId?: string;
            /** Format: uuid */
            walletId?: string;
            /** Format: uuid */
            paymentOrderId?: string;
            /** Format: uuid */
            transactionId?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "RECHARGED" | "FAILED" | "CANCELLED";
            amount?: number;
            currency?: string;
            redirectUrl?: string;
            providerReference?: string;
        };
        ApiResponseWalletRechargeOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["WalletRechargeOrderResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListWalletRechargeOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["WalletRechargeOrderResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CommercialPlanQuoteRequest: {
            addOnCodes?: string[];
            /** @enum {string} */
            billingPeriod?: "MONTHLY" | "YEARLY";
        };
        CommercialPlanQuoteResponse: {
            plan?: {
                code?: string;
            };
            addOns?: {
                code?: string;
            }[];
            billingPeriod?: string;
            lines?: components["schemas"]["CommercialPlanQuoteLine"][];
            total?: number;
            currency?: string;
        };
        CommercialPlanQuoteLine: {
            serviceCode?: string;
            amount?: number;
            currency?: string;
        };
        ApiResponseCommercialPlanQuoteResponse: {
            success?: boolean;
            data?: components["schemas"]["CommercialPlanQuoteResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CommercialPlanCheckoutRequest: {
            /** Format: uuid */
            organizationId?: string;
            addOnCodes?: string[];
            /** @enum {string} */
            billingPeriod?: "MONTHLY" | "YEARLY";
            clientId?: string;
            /** @enum {string} */
            provider?: "MYCOOLPAY" | "STRIPE";
            /** @enum {string} */
            method?: "MOBILE_MONEY" | "CARD";
            payerReference?: string;
            idempotencyKey?: string;
        };
        CommercialPlanCheckoutResponse: {
            /** Format: uuid */
            orderId?: string;
            /** Format: uuid */
            paymentOrderId?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "ACTIVE" | "FAILED" | "CANCELLED";
            amount?: number;
            currency?: string;
            redirectUrl?: string;
            providerReference?: string;
        };
        ApiResponseCommercialPlanCheckoutResponse: {
            success?: boolean;
            data?: components["schemas"]["CommercialPlanCheckoutResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CommercialPlanOrderResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            organizationId?: string;
            planCode?: string;
            addOnCodes?: string[];
            billingPeriod?: string;
            amount?: number;
            currency?: string;
            /** Format: uuid */
            paymentOrderId?: string;
            /** @enum {string} */
            status?: "PENDING_PAYMENT" | "ACTIVE" | "FAILED" | "CANCELLED";
        };
        ApiResponseCommercialPlanOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["CommercialPlanOrderResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListCommercialPlanOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["CommercialPlanOrderResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    savePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    quote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceBundleQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseServiceBundleQuoteResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseServiceBundleOrderResponse"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceBundleCheckoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseServiceBundleCheckoutResponse"];
                };
            };
        };
    };
    purchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubscriptionResponse"];
                };
            };
        };
    };
    createWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWalletRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
    recharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletRechargeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletRechargeOrderResponse"];
                };
            };
        };
    };
    refreshWalletRechargeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletRechargeOrderResponse"];
                };
            };
        };
    };
    getWalletRechargeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletRechargeOrderResponse"];
                };
            };
        };
    };
    listWalletRechargeOrders: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListWalletRechargeOrderResponse"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTransactionResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPaymentOrderResponse"];
                };
            };
        };
    };
    initiate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiatePaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentOrderResponse"];
                };
            };
        };
    };
    refresh_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentOrderResponse"];
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string;
            };
            path: {
                provider: "MYCOOLPAY" | "STRIPE";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    pricing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListServicePriceResponse"];
                };
            };
        };
    };
    history_1: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListServiceBundleOrderResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseServiceBundleOrderResponse"];
                };
            };
        };
    };
    quoteCommercialPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommercialPlanQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCommercialPlanQuoteResponse"];
                };
            };
        };
    };
    checkoutCommercialPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommercialPlanCheckoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCommercialPlanCheckoutResponse"];
                };
            };
        };
    };
    refreshCommercialPlanOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCommercialPlanOrderResponse"];
                };
            };
        };
    };
    listCommercialPlanOrders: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCommercialPlanOrderResponse"];
                };
            };
        };
    };
    getCommercialPlanOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCommercialPlanOrderResponse"];
                };
            };
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPlanResponse"];
                };
            };
        };
    };
    mySubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSubscriptionResponse"];
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTransactionResponse"];
                };
            };
        };
    };
    canOperate: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    getWalletByOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentOrderResponse"];
                };
            };
        };
    };
}
