/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plans/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlan"];
        put: operations["savePlan"];
        post?: never;
        delete: operations["deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{code}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/recharge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post: operations["initiate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders/callbacks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mySubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/{walletId}/can-operate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["canOperate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/wallets/owner/{ownerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWalletByOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SavePlanRequest: {
            code?: string;
            name?: string;
            description?: string;
            price?: number;
            currency?: string;
            /** Format: int32 */
            periodDays?: number;
            serviceCodes?: string[];
            active?: boolean;
        };
        ApiResponsePlanResponse: {
            success?: boolean;
            data?: components["schemas"]["PlanResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PlanResponse: {
            code?: string;
            name?: string;
            description?: string;
            price?: number;
            currency?: string;
            /** Format: int32 */
            periodDays?: number;
            serviceCodes?: string[];
            active?: boolean;
        };
        PurchaseRequest: {
            /** Format: uuid */
            organizationId?: string;
        };
        ApiResponseSubscriptionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        SubscriptionResponse: {
            /** Format: uuid */
            organizationId?: string;
            planCode?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            paidUntil?: string;
            active?: boolean;
        };
        CreateWalletRequest: {
            /** Format: uuid */
            ownerId?: string;
            ownerName?: string;
        };
        ApiResponseWalletResponse: {
            success?: boolean;
            data?: components["schemas"]["WalletResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        WalletResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ownerId?: string;
            ownerName?: string;
            balance?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TransactionRequest: {
            amount?: number;
            reference?: string;
        };
        ApiResponseTransactionResponse: {
            success?: boolean;
            data?: components["schemas"]["TransactionResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        TransactionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            walletId?: string;
            amount?: number;
            type?: string;
            status?: string;
            reference?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        InitiatePaymentRequest: {
            clientId?: string;
            serviceCode?: string;
            idempotencyKey?: string;
            amount?: number;
            currency?: string;
            /** @enum {string} */
            provider?: "MYCOOLPAY" | "STRIPE";
            /** @enum {string} */
            method?: "MOBILE_MONEY" | "CARD";
            payerReference?: string;
            description?: string;
            callbackUrl?: string;
        };
        ApiResponsePaymentOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["PaymentOrderResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PaymentOrderResponse: {
            id?: string;
            tenantId?: string;
            clientId?: string;
            serviceCode?: string;
            amount?: number;
            currency?: string;
            provider?: string;
            method?: string;
            payerReference?: string;
            status?: string;
            providerReference?: string;
            redirectUrl?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseString: {
            success?: boolean;
            data?: string;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPlanResponse: {
            success?: boolean;
            data?: components["schemas"]["PlanResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListSubscriptionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListTransactionResponse: {
            success?: boolean;
            data?: components["schemas"]["TransactionResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseBoolean: {
            success?: boolean;
            data?: boolean;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPaymentOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["PaymentOrderResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: unknown;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    savePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    purchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubscriptionResponse"];
                };
            };
        };
    };
    createWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWalletRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
    recharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTransactionResponse"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTransactionResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPaymentOrderResponse"];
                };
            };
        };
    };
    initiate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiatePaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentOrderResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentOrderResponse"];
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string;
            };
            path: {
                provider: "MYCOOLPAY" | "STRIPE";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPlanResponse"];
                };
            };
        };
    };
    mySubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSubscriptionResponse"];
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTransactionResponse"];
                };
            };
        };
    };
    canOperate: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    getWalletByOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentOrderResponse"];
                };
            };
        };
    };
}
